#!/bin/bash

scripts/mongo-start

# Убиваем предыдущий инстанс приложения
if [ -f run/node.pid ]; then
	cat run/node.pid | xargs kill
	rm run/node.pid
fi
	
export ITHANK_ENV=development
node server/app.js &