#!/bin/bash

# Запускаем монгу, если не работает
if [ ! -f run/mongod.pid ]; then
	mongod --pidfilepath run/mongod.pid --logpath run/mongod.log --logappend &
fi

# Убиваем предыдущий инстанс приложения
if [ -f run/node.pid ]; then
	cat run/node.pid | xargs kill
	rm run/node.pid
fi
	
export ITHANK_ENV=development
node server/app.js &