#!/bin/bash

# Убиваем монгу
if [ -f run/mongod.pid ]; then
	cat run/mongod.pid | xargs kill
	rm run/mongod.pid
fi

# Убиваем приложение
if [ -f run/node.pid ]; then
	cat run/node.pid | xargs kill
	rm run/node.pid
fi